### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by GogoFC** [javiercordero/simple-brightness#1]
No issues here, just thanks for awesome app.
Wonder what it looks like on your desktop.
I use dwm so it occupies a large space, but very cool slider, I didn't know what to expect so I just downloaded it to see :) 

I could not get xbacklight to work, people reported they had to go back to older video drivers to make it work so I gave up and searched for a new one.

![simplebrightness](https://user-images.githubusercontent.com/9360410/78675242-5ee41200-78aa-11ea-8459-3d4efc89f57d.png)

**Comment by Cuperino** [comment]
Happy to see you like it. This is (or perhaps was) an issue... Just added a line that sets the max height of the window to the size of its components. I don't know whether DWM will respect the new rule, but if it does, the program should now only stretch horizontally.

BTW, here's how simplebrightness looks unstretched on KDE Plasma, my current desktop:
![simplebrightness](https://imaginary.tech/wp-content/uploads/sites/4/2019/05/simplebrightness_v0.2.gif)

**Comment by Cuperino** [comment]
Alright, just tested on DWM! Apparently DWM does not respect max height and width limitations when opening the app in tiling mode. But if you open the app in floating mode, it opens right at its correct size.

My advice is configure DWM to always open simplebrightness in floating mode, using the width of your choice, at a corner of your preference.
